create table orders (
                           id int generated by default as identity primary key,
                           data varchar(8),
                           customer_id int not null references customers(id),
                           product_name varchar (100),
                           amount int
);

insert into orders (data, customer_id, product_name, amount) values ('31/12', 1, 'Milk', 100);
insert into orders (data, customer_id, product_name, amount) values ('28/11', 2, 'Cheese', 200);
insert into orders (data, customer_id, product_name, amount) values ('30/11', 1, 'Milk', 100);
insert into orders (data, customer_id, product_name, amount) values ('26/10', 4, 'Milk', 100);
insert into orders (data, customer_id, product_name, amount) values ('10/12', 1, 'Bread', 50);